#!/bin/bash
MASTER="vm1"
TARGETS="vm1 vm2 vm3 vm4"
set -e
for h in $TARGETS 
 do echo $h 
 sshpass -pcentos ssh-copy-id -o ControlPath=none $h 
 done
ceph-deploy new $MASTER
ceph-deploy install $MASTER
echo "osd pool default size = 2" >> ceph.conf
ceph-deploy mon create-initial
for h in $TARGETS
 do
  echo $h 
  ceph-deploy install $h
  #ssh -t $h "sudo -- sh -c ' umount /dev/vdb 
  #dd if=/dev/zero of=/dev/vdb count=2 '" 
  scp root@${h}:ceph-disks .
  for disk in $(cat ceph-disks) ;
  do
    ceph-deploy osd prepare ${h}:${disk}
    ceph-deploy osd activate ${h}:${disk}1
  done
 done
ceph-deploy admin $MASTER
ssh -t $MASTER "sudo -- sh -c 'chmod +r /etc/ceph/ceph.client.admin.keyring'"
ssh $MASTER ceph health
ceph-deploy mds create $MASTER
ceph-deploy rgw create $MASTER
